### ISSUE TITLE
`hideredirs=1` is missing in the links "Wikilinks" and "Transclusions".

### ISSUE THREAD

**Issue by Ashleycho35** [BrandonXLF/linkcount#5] opened 2021-12-04 09:38 UTC
`hideredirs=1` is missing in the links "Wikilinks" and "Transclusions".

__Originally posted by @nardog in https://github.com/BrandonXLF/linkcount/issues/1__

**Comment by BrandonXLF** [comment] 2022-01-01 20:15
Duplicate of #1. I might add it, but I'd like to find an option that will still allow indirect links to be viewed.

**Closed by BrandonXLF** 2022-01-01 20:15 UTC

**Comment by abirfo1** [comment] 2023-07-21 23:27
****
